// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QL_Hocsinh.Models;

namespace QL_Hocsinh.Migrations
{
    [DbContext(typeof(KetQuaHocTap))]
    partial class KetQuaHocTapModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QL_Hocsinh.Models.Khoa", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TenKhoa")
                        .HasMaxLength(400);

                    b.HasKey("ID");

                    b.ToTable("Khoas");
                });

            modelBuilder.Entity("QL_Hocsinh.Models.LopHocPhan", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("DiemCK");

                    b.Property<float>("DiemGK");

                    b.Property<int>("HocKi");

                    b.Property<string>("KhoaID");

                    b.Property<string>("Mon")
                        .HasMaxLength(200);

                    b.Property<string>("MonHocID");

                    b.Property<int>("NamHoc");

                    b.HasKey("ID");

                    b.HasIndex("KhoaID");

                    b.HasIndex("MonHocID");

                    b.ToTable("LopHocPhans");
                });

            modelBuilder.Entity("QL_Hocsinh.Models.MonHoc", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SoTinChi");

                    b.Property<string>("TenMon")
                        .HasMaxLength(200);

                    b.HasKey("ID");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("QL_Hocsinh.Models.SinhVien", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HoTen")
                        .HasMaxLength(200);

                    b.Property<string>("LopHocPhanID");

                    b.Property<DateTime>("Namsinh");

                    b.Property<string>("Phone")
                        .HasMaxLength(11);

                    b.HasKey("ID");

                    b.HasIndex("LopHocPhanID");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("QL_Hocsinh.Models.LopHocPhan", b =>
                {
                    b.HasOne("QL_Hocsinh.Models.Khoa", "Khoa")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("KhoaID");

                    b.HasOne("QL_Hocsinh.Models.MonHoc", "MonHoc")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MonHocID");
                });

            modelBuilder.Entity("QL_Hocsinh.Models.SinhVien", b =>
                {
                    b.HasOne("QL_Hocsinh.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("SinhViens")
                        .HasForeignKey("LopHocPhanID");
                });
#pragma warning restore 612, 618
        }
    }
}
